name: Deploy React App

on:
  push:
    branches:
      - main # Specify your target branch
      - "feature/**" # Specify your feature branches
    path-ignore:
      - "README.md" # Ignore changes to README.md
      - ".github/workflows/**" # Ignore changes to workflow files
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Print Node version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx vitest run
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: echo "Building React app..."
