name: Test case
on: push
jobs:
  testcase:
    runs-on: ubuntu-latest
    steps:
      - name: Greet user
        uses: actions/checkout@v7
      - name: Install Node version
      - uses: actions/setup-node@v7
        with:
          node-version: 20
      - name: Print Node version
        run: node -v

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
